# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d_eXZYApzJblbaM6y1Vwehakhe61s0Gq

## **Binary Classification**

**Step 1 : Import necessary libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt

"""**Step 2 : Import Dataset from kaggle**"""

! unzip "/content/drive/MyDrive/ML Lab/Diabetics.zip"

df = pd.read_csv("diabetes2.csv")
df.shape
df.head()

"""**Step 3 : Visualize the dataset**"""

plt.scatter(df.Glucose,df.Outcome)
#To add title to graph
plt.title(" Scatter Plot ")

#To add labels to X and Y axes
plt.xlabel('Glucose')
plt.ylabel('Outcome')

plt.show()

"""**Step 4 : Splitting the data**"""

from sklearn.model_selection import train_test_split

x = df[['Glucose']]
y = df['Outcome']

x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state= 42) 
print(x_train)
print(x_test)
print(y_train)
print(y_test)

len(x_train)

len(y_train)

import numpy as np

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train,y_train)

model.predict(x_test)

pred_l = model.predict_proba(x_test)

model.score(x_test,y_test)

